const {
  PORT: PORT_STR,
  DB_CONNECTION_URL,
  REVIEWER_INTERVAL_MS: REVIEWER_INTERVAL_MS_STR,
  REVIEWER_CONCURRENCY: REVIEWER_CONCURRENCY_STR,
  MIN_AMOUNT_PEERS: MIN_AMOUNT_PEERS_STR,
  MIN_AMOUNT_CHANNELS: MIN_AMOUNT_CHANNELS_STR,
} = process.env;

const REVIEWER_INTERVAL_MS = Number(REVIEWER_INTERVAL_MS_STR) || 30000;
const REVIEWER_CONCURRENCY = Number(REVIEWER_CONCURRENCY_STR) || 5;
const MIN_AMOUNT_PEERS = Number(MIN_AMOUNT_PEERS_STR) || 200;
const MIN_AMOUNT_CHANNELS = Number(MIN_AMOUNT_CHANNELS_STR) || 1;
const PORT = Number(PORT_STR) || 3050;
const METRIC_PREFIX = "availability_monitor";

export {
  DB_CONNECTION_URL,
  REVIEWER_INTERVAL_MS,
  REVIEWER_CONCURRENCY,
  MIN_AMOUNT_PEERS,
  MIN_AMOUNT_CHANNELS,
  PORT,
  METRIC_PREFIX,
};
