#!/usr/bin/env bash

source /usr/local/lib/bash-logger.sh
source /usr/local/lib/persist-env.sh

NOTICE "[RPC-SERVER] -- Starting Service rpc-server ..."

# load docker env vars
export $(grep -v '^#' /docker.env | xargs -0)

# let rpc-server run on internal port
export PORT=45752

exec chpst -u node /usr/bin/node /app/build/index.js 2>&1
