# docker-compose file that allows you locally host
# the centralized apps that make RPCh work
# DO NOT USE IN PRODUCTION
# launches:
#   - 1 availability monitor
version: '3'

volumes:
    # postgres database
    postgres-data:

services:
    availability-monitor:
        build:
            dockerfile: apps/availability-monitor/Dockerfile
            context: ../../../
        restart: unless-stopped
        ports:
            - '9080:9080'
        network_mode: 'host'
        environment:
            - DEBUG=${DEBUG}
            - PORT=9080
            - PGUSER=${POSTGRES_USER}
            - PGPASSWORD=${POSTGRES_PASSWORD}
            - PGHOST=host.docker.internal
            - PGPORT=5432
            - PGDATABASE=postgres
